apiVersion: batch/v1
kind: Job
metadata:
  name: one
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job one (PreSync wave 1) && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: two
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job two (PreSync wave 2) && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: three
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job three (Sync wave 1) && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: four
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job four (Sync wave 2) && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: five
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job five (Sync wave 3) && sleep 5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: six
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job six (PostSync wave 1) && sleep 5"]
      restartPolicy: Never
